import { ICategory } from "../category/category";

// Generated by https://quicktype.io
export interface IProduct {
    _id:         string;
    name:        string;
    slug:        string;
    description: string;
    images:      string[];
    price:       string;
    stock:       number;
    category:    ICategory;
    createdAt:   string;
    updatedAt:   string;
}

