// Generated by https://quicktype.io

import { Category } from "../category/category";

export interface Product {
    id:          string;
    name:        string;
    slug:        string;
    stock:       number;
    price:       number;
    description: string;
    category:    Category;
    images:      Image[];
}

export interface Image {
    id:  number;
    url: string;
}
